package actuarial

import (
	"encoding/json"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/persense/persense-port/internal/types"
)

// TestSULTvsActuarialMath validates the Go actuarial engine against an
// INDEPENDENT third-party oracle: the SOA Standard Ultimate Life Table (SULT,
// Makeham's Law A=0.00022 B=2.7e-6 c=1.124, i=5%) and the open-source
// `actuarialmath` Python library. testdata/sult_reference.json carries the
// SULT lx table plus reference survival probabilities, curtate life
// expectancies, whole-life annuities, whole-life insurances (all from
// actuarialmath, matching the SOA's published SULT values), and a
// DOS-convention Payment-on-Death value.
//
// The reference is regenerated by the Python block in
// docs/actuarial_sult_validation.md. Since the DOS actuarial core is absent
// from the snapshot (see docs/actuarial_oracle_blocked.md), this is the
// strongest available external check: it confirms the Go life-contingency math
// reproduces an authoritative third-party computation, even though it cannot
// confirm bit-fidelity to the (missing) original 1988-table DOS outputs.
func TestSULTvsActuarialMath(t *testing.T) {
	raw, err := os.ReadFile("testdata/sult_reference.json")
	if err != nil {
		t.Skipf("SULT reference not present: %v", err)
	}
	var ref struct {
		Params     struct{ I float64 } `json:"params"`
		Lx         []float64           `json:"lx"`
		Kpx        map[string]float64  `json:"kpx"`
		Ex         map[string]float64  `json:"ex"`
		AnnuityDue map[string]float64  `json:"annuity_due"`
		Insurance  map[string]float64  `json:"insurance"`
		PodDOS     map[string]float64  `json:"pod_dos"`
	}
	if err := json.Unmarshal(raw, &ref); err != nil {
		t.Fatalf("bad reference json: %v", err)
	}

	tbl := NewLifeTableFromLx("SULT", ref.Lx)
	i := ref.Params.I
	v := 1.0 / (1 + i)
	delta := math.Log(1 + i)

	// (1) Survival probabilities kpx — the convention-independent core, vs the
	// authoritative SULT / actuarialmath values.
	survFails, survMax := 0, 0.0
	for key, want := range ref.Kpx {
		x, k := parseXK(t, key)
		got := tbl.ConditionalSurvival(float64(x), float64(x+k))
		// Also exercise the LifeProb(Living) dispatch path.
		gotLP := lifeProbLiving(tbl, x, k)
		d := math.Abs(got - want)
		if dlp := math.Abs(gotLP - want); dlp > d {
			d = dlp
		}
		if d > survMax {
			survMax = d
		}
		if d > 1e-9 {
			survFails++
			if survFails <= 8 {
				t.Errorf("kpx[%d,%d]: SULT=%.10f Go=%.10f (LifeProb=%.10f)", x, k, want, got, gotLP)
			}
		}
	}
	t.Logf("survival kpx vs SULT/actuarialmath: %d points, fails %d, max |err|=%.2e", len(ref.Kpx), survFails, survMax)

	// (2) Curtate life expectancy e_x — the engine's own LifeExpectancy().
	exFails, exMax := 0, 0.0
	for key, want := range ref.Ex {
		x := atoi(t, key)
		got := tbl.LifeExpectancy(float64(x))
		d := math.Abs(got - want)
		if d > exMax {
			exMax = d
		}
		if d > 1e-4 {
			exFails++
			t.Errorf("e_%d: SULT=%.6f Go=%.6f", x, want, got)
		}
	}
	t.Logf("life expectancy e_x vs SULT: %d ages, fails %d, max |err|=%.2e", len(ref.Ex), exFails, exMax)

	// (3) Whole-life annuity-due and whole-life insurance, built from the
	// engine's survival with the standard actuarial convention, vs the SULT.
	annFails, insFails, annMax, insMax := 0, 0, 0.0, 0.0
	for key, wantAnn := range ref.AnnuityDue {
		x := atoi(t, key)
		var ann, ins float64
		for k := 0; x+k <= tbl.MaxAge(); k++ {
			kp := tbl.ConditionalSurvival(float64(x), float64(x+k))
			kp1 := tbl.ConditionalSurvival(float64(x), float64(x+k+1))
			ann += math.Pow(v, float64(k)) * kp           // ä_x = Σ vᵏ ·ₖpₓ
			ins += math.Pow(v, float64(k+1)) * (kp - kp1) // A_x = Σ vᵏ⁺¹·(ₖpₓ−ₖ₊₁pₓ)
		}
		if d := math.Abs(ann - wantAnn); d > annMax {
			annMax = d
		}
		if math.Abs(ann-wantAnn) > 1e-4 {
			annFails++
			t.Errorf("annuity ä_%d: SULT=%.6f Go=%.6f", x, wantAnn, ann)
		}
		wantIns := ref.Insurance[key]
		if d := math.Abs(ins - wantIns); d > insMax {
			insMax = d
		}
		if math.Abs(ins-wantIns) > 1e-5 {
			insFails++
			t.Errorf("insurance A_%d: SULT=%.6f Go=%.6f", x, wantIns, ins)
		}
	}
	t.Logf("annuity ä_x vs SULT: fails %d, max |err|=%.2e | insurance A_x: fails %d, max |err|=%.2e",
		annFails, annMax, insFails, insMax)

	// (4) The engine's OWN Payment-on-Death code (PODValue, DOS mid-year /
	// continuous convention) vs a reference computed with the same convention
	// from the SULT survival. POD is scaled up so the engine's Round2 keeps
	// precision, then normalised.
	const pod = 1e8
	podFails, podMax := 0, 0.0
	now := types.NewDateRec(2024, time.January, 1)
	for key, want := range ref.PodDOS {
		x := atoi(t, key)
		cfg := &ActuarialConfig{
			Table1: tbl,
			DOB1:   types.NewDateRec(2024-x, time.January, 1), // age x at `now`
			Now:    now,
			POD:    pod,
		}
		got := cfg.PODValue(now, delta) / pod
		d := math.Abs(got - want)
		if d > podMax {
			podMax = d
		}
		if d > 1e-6 {
			podFails++
			t.Errorf("PODValue (A_%d, DOS convention): ref=%.8f Go=%.8f", x, want, got)
		}
	}
	t.Logf("PODValue (DOS convention) vs SULT-survival reference: fails %d, max |err|=%.2e", podFails, podMax)
}

func lifeProbLiving(tbl *LifeTable, x, k int) float64 {
	cfg := &ActuarialConfig{
		Table1: tbl,
		DOB1:   types.NewDateRec(2024-x, time.January, 1),
		Now:    types.NewDateRec(2024, time.January, 1),
	}
	return cfg.LifeProb(types.NewDateRec(2024+k, time.January, 1), Living)
}

func parseXK(t *testing.T, key string) (int, int) {
	p := strings.Split(key, ",")
	if len(p) != 2 {
		t.Fatalf("bad kpx key %q", key)
	}
	return atoi(t, p[0]), atoi(t, p[1])
}

func atoi(t *testing.T, s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		t.Fatalf("bad int %q: %v", s, err)
	}
	return n
}
