// Package finance provides cross-check tests that verify the Go port against
// reference data generated by the original Pascal code compiled with Free Pascal.
//
// The reference data is in legacy/reference-output/refdata.json, generated by
// legacy/testharness/refdata.pas.
package finance

import (
	"encoding/json"
	"math"
	"os"
	"testing"
	"time"

	"github.com/persense/persense-port/internal/dateutil"
	"github.com/persense/persense-port/internal/finance/interest"
	"github.com/persense/persense-port/internal/finance/mortgage"
	"github.com/persense/persense-port/internal/finance/presentvalue"
	"github.com/persense/persense-port/internal/types"
)

// refData holds the parsed reference JSON
type refData struct {
	JulianRoundtrip []struct {
		Year  int `json:"year"`
		Month int `json:"month"`
		Day   int `json:"day"`
		Jul   int64 `json:"julian"`
		RTD   int `json:"rt_d"`
		RTM   int `json:"rt_m"`
		RTY   int `json:"rt_y"`
	} `json:"julian_roundtrip"`

	Exxp []struct {
		Input  float64 `json:"input"`
		Output float64 `json:"output"`
	} `json:"exxp"`

	Lnn []struct {
		Input  float64 `json:"input"`
		Output float64 `json:"output"`
	} `json:"lnn"`

	Power []struct {
		X      float64 `json:"x"`
		N      float64 `json:"n"`
		Output float64 `json:"output"`
	} `json:"power"`

	Round2 []struct {
		Input  float64 `json:"input"`
		Output float64 `json:"output"`
	} `json:"round2"`

	YieldRateRoundtrip []struct {
		Rate      float64 `json:"rate"`
		PerYr     int     `json:"peryr"`
		Yield     float64 `json:"yield"`
		Roundtrip float64 `json:"roundtrip"`
	} `json:"yield_rate_roundtrip"`

	MortgageSummation []struct {
		Rate   float64 `json:"rate"`
		Years  float64 `json:"years"`
		Output float64 `json:"output"`
	} `json:"mortgage_summation"`

	MortgageCalc []struct {
		Price      float64 `json:"price"`
		Pct        float64 `json:"pct"`
		Years      int     `json:"years"`
		Rate       float64 `json:"rate"`
		Financed   float64 `json:"financed"`
		Summation  float64 `json:"summation"`
		Monthly    float64 `json:"monthly"`
	} `json:"mortgage_calc"`

	PVSumFormula []struct {
		Lnf    float64 `json:"lnf"`
		N      float64 `json:"n"`
		Output float64 `json:"output"`
	} `json:"pv_sumformula"`

	YearsDif []struct {
		From     string  `json:"from"`
		To       string  `json:"to"`
		Basis360 float64 `json:"basis360"`
		Basis365 float64 `json:"basis365"`
	} `json:"yearsdif"`
}

func loadRefData(t *testing.T) *refData {
	t.Helper()
	// Try multiple paths since tests run from different directories
	paths := []string{
		"../../legacy/reference-output/refdata.json",
		"../legacy/reference-output/refdata.json",
		"legacy/reference-output/refdata.json",
	}
	var data []byte
	var err error
	for _, p := range paths {
		data, err = os.ReadFile(p)
		if err == nil {
			break
		}
	}
	if err != nil {
		t.Fatalf("cannot read refdata.json: %v (tried %v)", err, paths)
	}
	var ref refData
	if err := json.Unmarshal(data, &ref); err != nil {
		t.Fatalf("cannot parse refdata.json: %v", err)
	}
	return &ref
}

func assertClose(t *testing.T, label string, got, want, tol float64) {
	t.Helper()
	diff := math.Abs(got - want)
	if want != 0 {
		relErr := diff / math.Abs(want)
		if relErr > tol && diff > 1e-12 {
			t.Errorf("%s: got %.15g, want %.15g (relErr=%.2e)", label, got, want, relErr)
		}
	} else if diff > tol {
		t.Errorf("%s: got %.15g, want 0", label, got)
	}
}

// --- Cross-check tests ---

func TestCrossCheckJulian(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.JulianRoundtrip {
		month := tc.Month
		day := tc.Day
		if month == 0 { month = 1 }
		if day == 0 { day = 1 }
		d := types.NewDateRec(tc.Year, time.Month(month), day)
		j := dateutil.Julian(d)
		if j != tc.Jul {
			t.Errorf("Julian(%d-%02d-%02d): got %d, pascal %d", tc.Year, month, day, j, tc.Jul)
		}
		// Round trip
		rt, err := dateutil.MDY(j)
		if err != nil {
			t.Errorf("MDY(%d) error: %v", j, err)
			continue
		}
		if rt.Time.Day() != tc.RTD || int(rt.Time.Month()) != tc.RTM || rt.Time.Year() != tc.RTY {
			t.Errorf("MDY(%d): got %d-%02d-%02d, pascal %d-%02d-%02d",
				j, rt.Time.Year(), rt.Time.Month(), rt.Time.Day(), tc.RTY, tc.RTM, tc.RTD)
		}
	}
}

func TestCrossCheckExxp(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.Exxp {
		got, err := interest.Exxp(tc.Input)
		if err != nil {
			t.Errorf("Exxp(%g) error: %v", tc.Input, err)
			continue
		}
		assertClose(t, "Exxp("+formatFloat(tc.Input)+")", got, tc.Output, 1e-10)
	}
}

func TestCrossCheckLnn(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.Lnn {
		got, err := interest.Lnn(tc.Input)
		if err != nil {
			t.Errorf("Lnn(%g) error: %v", tc.Input, err)
			continue
		}
		assertClose(t, "Lnn("+formatFloat(tc.Input)+")", got, tc.Output, 1e-10)
	}
}

func TestCrossCheckPower(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.Power {
		got, err := interest.Power(tc.X, tc.N)
		if err != nil {
			t.Errorf("Power(%g,%g) error: %v", tc.X, tc.N, err)
			continue
		}
		assertClose(t, "Power("+formatFloat(tc.X)+","+formatFloat(tc.N)+")", got, tc.Output, 1e-10)
	}
}

func TestCrossCheckRound2(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.Round2 {
		got := interest.Round2(tc.Input)
		if got != tc.Output {
			t.Errorf("Round2(%g): got %g, pascal %g", tc.Input, got, tc.Output)
		}
	}
}

func TestCrossCheckYieldRate(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.YieldRateRoundtrip {
		y, err := interest.YieldFromRate(tc.Rate, byte(tc.PerYr), 365.25)
		if err != nil {
			t.Errorf("YieldFromRate(%g, %d) error: %v", tc.Rate, tc.PerYr, err)
			continue
		}
		assertClose(t, "YieldFromRate("+formatFloat(tc.Rate)+")", y, tc.Yield, 1e-10)

		r, err := interest.RateFromYield(y, byte(tc.PerYr), 365.25)
		if err != nil {
			t.Errorf("RateFromYield error: %v", err)
			continue
		}
		assertClose(t, "RateFromYield roundtrip", r, tc.Rate, 1e-10)
	}
}

func TestCrossCheckMortgageSummation(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.MortgageSummation {
		got, err := mortgage.Summation(tc.Rate, tc.Years)
		if err != nil {
			t.Errorf("Summation(%g, %g) error: %v", tc.Rate, tc.Years, err)
			continue
		}
		assertClose(t, "Summation("+formatFloat(tc.Rate)+","+formatFloat(tc.Years)+")",
			got, tc.Output, 1e-10)
	}
}

func TestCrossCheckMortgageCalc(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.MortgageCalc {
		m := mortgage.MtgLine{
			PriceStatus: types.InOutInput,
			Price:       tc.Price,
			PctStatus:   types.InOutInput,
			Pct:         tc.Pct,
			YearsStatus: types.InOutInput,
			Years:       tc.Years,
			RateStatus:  types.InOutInput,
			Rate:        tc.Rate,
			TaxStatus:   types.InOutInput,
			Tax:         0,
			BalloonStat: types.BalloonBlank,
		}
		result := mortgage.Calc(m)
		if result.Err != nil {
			t.Errorf("Calc(price=%g,pct=%g,yrs=%d,rate=%g) error: %v",
				tc.Price, tc.Pct, tc.Years, tc.Rate, result.Err)
			continue
		}
		assertClose(t, "financed", result.Line.Financed, tc.Financed, 1e-10)
		assertClose(t, "monthly", result.Line.Monthly, tc.Monthly, 1e-10)
	}
}

func TestCrossCheckPVSumFormula(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.PVSumFormula {
		got, err := presentvalue.SumFormula(tc.Lnf, tc.N)
		if err != nil {
			t.Errorf("SumFormula(%g, %g) error: %v", tc.Lnf, tc.N, err)
			continue
		}
		assertClose(t, "SumFormula("+formatFloat(tc.Lnf)+","+formatFloat(tc.N)+")",
			got, tc.Output, 1e-10)
	}
}

func TestCrossCheckYearsDif(t *testing.T) {
	ref := loadRefData(t)
	for _, tc := range ref.YearsDif {
		from := parseDate(t, tc.From)
		to := parseDate(t, tc.To)

		got360 := dateutil.YearsDif(to, from, types.Basis360, 1.0/365.25, false)
		assertClose(t, "YearsDif360("+tc.From+"→"+tc.To+")", got360, tc.Basis360, 1e-10)

		got365 := dateutil.YearsDif(to, from, types.Basis365, 1.0/365.25, false)
		// YearsDif365 involves Julian() which chains multiple integer and float ops.
		// Pascal real vs Go float64 accumulate differently at ~1e-8 level.
		assertClose(t, "YearsDif365("+tc.From+"→"+tc.To+")", got365, tc.Basis365, 1e-7)
	}
}

// --- helpers ---

func parseDate(t *testing.T, s string) types.DateRec {
	t.Helper()
	d, err := time.Parse("2006-01-02", s)
	if err != nil {
		t.Fatalf("bad date %q: %v", s, err)
	}
	return types.NewDateRec(d.Year(), d.Month(), d.Day())
}

func formatFloat(f float64) string {
	if f == float64(int64(f)) {
		return string(rune(int64(f) + '0'))
	}
	return ""
}
